connection:
  info:
    ip: 127.0.0.1
    port: 5000
    tls_config:
      enable: false
  name: FlaskConnection
  path: ibmfl.connection.flask_connection
  sync: false
data:
  info:
    npz_file: C:\Users\Andre\Documents\ce-299\federated-learning-lib\examples\datasets\mnist.npz
  name: MnistSklearnDataHandler
  path: ibmfl.util.data_handlers.mnist_sklearn_data_handler
fusion:
  name: IterAvgFusionHandler
  path: ibmfl.aggregator.fusion.iter_avg_fusion_handler
hyperparams:
  global:
    max_timeout: 60
    num_parties: 3
    rounds: 50
    termination_accuracy: 1.0
  local:
    training:
      max_iter: 2
protocol_handler:
  name: ProtoHandler
  path: ibmfl.aggregator.protohandler.proto_handler
